### ISSUE TITLE
Beta reduction scoping/alphatizing error

### ISSUE THREAD

**Issue by themattchan** [ucsd-progsys/elsa#4]
The following valid reduction fails:

```
eval and_true_false :
  AND TRUE FALSE
...
  =b> (\x y -> (\x y -> x) x y)  (\x y -> y) FALSE
  =b> (\y -> (\x y -> x) (\x y -> y) y) FALSE
  ...
  =d> FALSE
```

with error 

```Errors found!
01_bool.lc:35:3-7: and_true_false has an invalid reduction!

        35|    =b> (\y -> (\x y -> x) (\x y -> y) y) FALSE
               ^^^^
```

I think using a de Bruijn-based representation internally will fix this? (Not sure if that's already the case)

**Comment by ranjitjhala** [comment]
Oops, looks like I've messed something up in `substCA` 

https://github.com/ucsd-progsys/elsa/blob/master/src/Language/Elsa/Eval.hs#L173-L186

as it works if one alpha-renames the variables `x0`,`x1`,`y0`,`y1` 

will take a look ASAP!

**Comment by ranjitjhala** [comment]
Fixed by https://github.com/ucsd-progsys/elsa/pull/5
