### ISSUE TITLE
Couldn't match expected type ‘Int’ with actual type ‘Pos’

### ISSUE THREAD

**Issue by Caagr98** [ucsd-progsys/elsa#7]
When trying to install this with cabal, I get the following error:
[elsa.txt](https://github.com/ucsd-progsys/elsa/files/2020736/elsa.txt)

The same error occurs when cloning and compiling the repo.

**Comment by ranjitjhala** [comment]
Are you using `stack` ? I just did a fresh clone and it builds fine if you do:

```
$ git clone git@github.com:ucsd-progsys/elsa.git
$ cd elsa
$ stack build
```

**Comment by Caagr98** [comment]
Huh, that worked (with a warning about unused mapMaybe and isAId). Weird. Did Cabal get some dependency wrong or something?

Anyway, copying the compiled executable to my $PATH seems to work. Problem kinda solved, I guess.
