### ISSUE TITLE
stack install command still running after half an hour?

### ISSUE THREAD

**Issue by jakrosh** [ucsd-progsys/elsa#9]
The stack install command has been "Installing GHC... " for the past 30 mins, is this normal?

**Comment by ranjitjhala** [comment]
depends on how fast your connection is; if you're doing it for the first
time, its downloading the whole GHC compiler and building it...

**Comment by jakrosh** [comment]
I think my connection is fine, It seems that there is some issue with running these running the setup commands on WSL. 
https://github.com/microsoft/WSL/issues/1671

**Comment by ranjitjhala** [comment]
Oops, that may be it :-(
